env:
  browser: true
  node: true
  es6: true
extends:
  - plugin:@wordpress/eslint-plugin/recommended
  - plugin:import/warnings
ignorePatterns:
  - jest.config.js
  - webpack.config.js
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - import
root: true
rules:
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
      newlines-between: always