env:
  browser: true
  node: true
  es6: true
extends:
  - plugin:@wordpress/eslint-plugin/recommended-with-formatting
  - plugin:@typescript-eslint/recommended
  - plugin:import/warnings
ignorePatterns:
  - jest.config.js
  - webpack.config.js
overrides: 
-
  files: 
  - "src/types/*.ts"
  rules: 
    camelcase: "off"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - import
root: true
rules:
  "@typescript-eslint/ban-ts-comment": off
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
      newlines-between: always
settings: 
  import/resolver: 
    typescript: 
      project: "./"